<?php include('essentials/top.php'); ?>
<?php include('includes/header.php'); ?>
<section class='policy-sec'>
	<div class="container">
		<h1>Privacy Policy</h1>
		<hr class="header-line" />
		<h3>General</h3>
		<p>By using, accessing or participating in the Service, you agree to the terms of this privacy policy (the "Privacy Policy"). Capitalized terms not defined in this Privacy Policy have the meanings set forth in the Terms and Conditions, located here. We reserve the right to change our Privacy Policy at any time. If we do this, we will post a notice that we have made changes to this Privacy Policy on the Website for at least 7 days after the changes are posted and will indicate at the bottom of the Privacy Policy the date these terms were last revised. Any revisions to this Privacy Policy will become effective the earlier of (i) the end of the foregoing 7-day period or (ii) the first time you access or use the Service after any such changes. If you do not agree to abide by this Privacy Policy, you are not authorized to use, access or participate in the Service.</p>
		<h3>Information We Collect</h3>
		<p>When you use the Service you provide us with two types of information: (i) information you submit via the Service and (ii) information regarding your use of the Service collected by us as you interact with the Service.</p>
		<p>When you enter the Website, we collect your browser type and IP address. This information is gathered for all Website visitors. In addition, we store certain information from your browser using "cookies." A cookie is a piece of data stored on the user's computer tied to information about the user. We use session ID cookies to confirm that users are logged in. If you do not want information collected through the use of cookies, there is a simple procedure in most browsers that allows you to deny or accept the cookie feature; however, you should note that cookies may be necessary to provide you certain features (e.g., customized delivery of information) available on the Website.</p>
		<p>Through the registration process you may provide us with your name, phone number, email address, hometown, and other information that may be requested during the registration process. When you use the Service you may submit information and content to your profile, generate Activity Data through engaging in educational activities on the Service, or send messages and otherwise transmit information to other users. We store this information so that we can provide you the Service and offer personalized features.</p>
		<h3>User Of Information Obtained by TestsGenie</h3>
		<p>We may use your contact information to send you notifications regarding new services offered by TestsGenie and its partners that we think you may find valuable. TestsGenie may also send you service-related announcements from time to time through the general operation of the Service. Generally, you may opt out of such emails, although TestsGenie reserves the right to send you notices about your account even if you opt out of all voluntary email notifications.</p>
		<p>Profile information is used by TestsGenie primarily to be presented back to and edited by you when you access the Service and to be presented to other users. In some cases, other users may be able to supplement your profile, including by submitting comments.</p>
		<p>TestsGenie may use aggregate or anonymous data collected through the Service, including Activity Data, for any purpose. This data may be used by TestsGenie and shared with third parties in any manner.</p>
		<h3>Sharing Your Personally-Identifiable Information with Third Parties</h3>
		<p>TestsGenie shares your personally-identifiable information only in limited circumstances where TestsGenie believes such sharing is reasonably necessary to offer the Service, legally required or, permitted by you. For example: We may provide personally-identifiable information to service providers who help us bring you the Service, such as hosting the Service at a co-location facility or sending email updates. In connection with these operations, our service providers may have access to personally-identifiable information for use for a limited time. Where we utilize service providers for the processing of any of personally-identifiable information, we implement reasonable contractual protections limiting the use of that personally-identifiable information to the provision of services to TestsGenie.</p>
		<p>Notwithstanding anything else in this policy, we may work with partners who use mobile SDKs, including the XXX Messaging SDK, to passively collect information (collectively, “SDK Information”), which generally helps us deliver personalized notifications. This data may also be used to identify you in a unique manner across other devices or browsers for the purposes of customizing ads or content. Depending on the permissions granted to this application, this information may include personally identifiable information (PII) including your e-mail address. This information may also include precise location (i.e. GPS-level data) or WiFi information, apps you have installed and enabled, and your mobile identifier (e.g., Android Advertising ID).</p>
		<h3>Consumer Control & Opt-Out Options</h3>
		<ul>
			<li><b>Opting-out of XXX Push Notifications</b> - You may in most cases opt out of receiving push notifications by going to your device “Settings” and clicking on “Notifications,” and then changing those settings for some or all of the apps on your device. (Different device configurations, or updates to devices, may affect or change how these settings work.)</li>
			<li><b>Opting Out of “Cross-App” Advertising on Mobile Devices</b> - You can opt out of having your mobile advertising identifiers used for certain types of interest-based (also called “cross-app”) mobile behavioral advertising, by accessing the “settings” on your Apple or Android mobile device, as follows: By opening the Google Settings app on your device, selecting Ads, and then selecting the option to opt-out of interest-based ads. (Different device configurations, or updates to devices, may affect or change how these settings work.)</li>
		</ul>
		<p>We may be required to disclose personally-identifiable information pursuant to lawful requests, such as subpoenas or court orders, or in compliance with applicable laws. Additionally, we may share account or other personally-identifiable information when we believe it is necessary to comply with law, to protect our interests or property, to prevent fraud or other illegal activity perpetrated through the Service or using the TestsGenie name, or to prevent imminent harm. This may include sharing personally-identifiable information with other companies, lawyers, agents or government agencies.</p>
		<p>If the ownership of all or substantially all of the TestsGenie business, or individual business units or assets owned by TestsGenie that are related to the Service, were to change, your personally-identifiable information may be transferred to the new owner. In any such transfer of information, your personally-identifiable information would remain subject to this section.</p>
		<h3>Links</h3>
		<p style="margin-bottom: 20px;">The Service may contain links to other websites. We are not responsible for the privacy practices of other websites. We encourage users to be aware when they leave the Service to read the privacy statements of other websites that collect personally identifiable information. This Privacy Policy applies solely to information collected by TestsGenie via the Service. We may also integrate with third parties who will interact with you under their terms of service. One such third party is YouTube and by using the Sites or Services, you agree to be bound by the YouTube Terms of Service located <a href="https://www.youtube.com/t/terms" target="_blank">here</a> and also by the privacy policies of Google located <a href="https://policies.google.com/privacy" target="_blank">here</a>. We use YouTube APIs to show you the video views count and Embed YouTube videos on Free Videos page</p>
	</div>
</section>
 
<?php include('includes/footer.php'); ?>